#!/bin/sh
LAUNCHPAD_SHIFTED_ARGS=
LAUNCHPAD_SKIPPED_ARG_1=
export LAUNCHPAD_SHIFTED_ARGS
export LAUNCHPAD_SKIPPED_ARG_1

for arg in $*; do
	if [ "$LAUNCHPAD_SKIPPED_ARG_1" = "" ]; then
		LAUNCHPAD_SKIPPED_ARG_1=true; export LAUNCHPAD_SKIPPED_ARG_1
	else
		LAUNCHPAD_SHIFTED_ARGS="$LAUNCHPAD_SHIFTED_ARGS $arg"; export LAUNCHPAD_SHIFTED_ARGS
	fi
done


$LAUNCHPAD_SHIFTED_ARGS

LAUNCHPAD_EXEC_RETURN_CODE=$?; export LAUNCHPAD_EXEC_RETURN_CODE
echo $LAUNCHPAD_EXEC_RETURN_CODE >$1
exit $LAUNCHPAD_EXEC_RETURN_CODE
